# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: maximilianhenrich
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Maximilian Henrich portfolio site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: monofaktur
github_username:  monofaktur

languages: ["de", "en", "jp"]
default_lang: "de"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false

# Build settings
markdown: kramdown
permalink: pretty
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]
