# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: maximilianhenrich
email: hello@maximilianhenrich.de
description: > # this means to ignore newlines until "baseurl:"
  Maximilian Henrich portfolio site
baseurl: "" # the subpath of your site, e.g. /blog
url: "maximilianhenrich.de" # the base hostname & protocol for your site

# Contact details
fullname: Maximilian Henrich
address: DÃ¼sseldorf, Germany
twitter_username: mojitane
github_username:  mojitane

cta_text:
  de: Jetzt ein Projekt beginnen!
  en: Let's talk about your project!
  jp: ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã‚’å§‹ã‚ã‚ˆã†ï¼
details_linktext:
  de: Details
  en: Details
  jp: è©³ã—ã
visit_linktext:
  de: Besuchen
  en: View live
  jp: ã‚µã‚¤ãƒˆã‚’è¦‹ã‚‹
contat-form-help:
  de: GroÃŸartige Ideen sollten nicht warten mÃ¼ssen! ğŸ’»
  en: Great ideas shouldn't have to wait! ğŸ’»
  jp: Great ideas shouldn't have to wait! ğŸ’»
contat-form-title:
  de: Jetzt Anfragen!
  en: Get started now!
  jp: ã‚³ãƒ³ã‚¿ã‚¯ãƒˆ
contat-form-from:
  de: Absender
  en: From
  jp: ãƒ¡ãƒ¼ãƒ«
contat-form-message:
  de: Nachricht
  en: Message
  jp: ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸

languages: ["de", "en", "jp"]
default_lang: "de"
exclude_from_localization: ["javascript", "images", "css", "assets"]
parallel_localization: false

# Build settings
markdown: kramdown
permalink: /projects/:title/
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]
